# Background and foreground colors
background = #09111D
foreground = #F1EBD3

# Standard colors
palette = 0=#09111D
palette = 1=#a79a56
palette = 2=#c2cf7a
palette = 3=#f8fe94
palette = 4=#689153
palette = 5=#ceab4c
palette = 6=#c9ed82
palette = 7=#F1EBD3

# Bright colors
palette = 8=#686b71
palette = 9=#c0b058
palette = 10=#d8e876
palette = 11=#f5fc72
palette = 12=#76a95c
palette = 13=#ecbf3c
palette = 14=#d9ff7d
palette = 15=#f5f6eb
