$color = rgba(9, 17, 29, 1)
$inner_color = rgba(9, 17, 29, 0.66)
$outer_color = rgba(206, 171, 76, 1)
$font_color = rgba(241, 235, 211, 1)
$placeholder_color = rgba(241, 235, 211, 0.7)
$check_color = rgba(201, 237, 130, 1)
