background            #09111D
foreground            #F1EBD3

# black
color0  #09111D
color8  #686b71

# red
color1  #a79a56
color9  #c0b058

# green
color2  #c2cf7a
color10 #d8e876

# yellow
color3  #f8fe94
color11 #f5fc72

# blue
color4  #689153
color12 #76a95c

# magenta
color5  #ceab4c
color13 #ecbf3c

#cyan
color6  #c9ed82
color14 #d9ff7d

#white
color7  #F1EBD3
color15 #f5f6eb


